version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./iva_backend/Dockerfile
    command: gunicorn iva_backend.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - IVA_URL=http://iva:8001
    expose:
      - 8000
    depends_on:
      - db
      - redis
    networks:
      - backend
      - iva_network
    labels:
      - traefik.enable=false

  celery:
    build:
      context: .
      dockerfile: ./iva_backend/Dockerfile
    command: celery --app=iva_backend worker -B --loglevel=info
    volumes:
      - .:/usr/src/app/
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
    networks:
      - backend
      - iva_network
    labels:
      - traefik.enable=false

  redis:
    image: redis:5-alpine
    networks:
      - backend
    labels:
      - traefik.enable=false

  backend_web:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8000:80
    depends_on:
      - app
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:iva-backend.docker.localhost
      - traefik.docker.network=iva_network
    networks:
      - iva_network
      - backend

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=homestead
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWORD=secret
    ports:
    - 33061:3306
    networks:
      - backend
    labels:
      - traefik.enable=false

volumes:
  dbdata:
  static_volume:

networks:
  iva_network:
      name: iva_network

  backend:
