# Generated by Django 3.1.3 on 2021-05-18 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_approved_field_to_training_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindfulSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=128)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
