# Generated by Django 3.2.3 on 2021-06-22 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_mindful_session_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepAnalysis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=128)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(choices=[(0, 'In Bed'), (1, 'Asleep'), (2, 'Awake')])),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
