# Generated by Django 3.2.3 on 2021-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_sleep_analysis_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('ML', 'ml'), ('MG', 'mg'), ('PACKAGE', 'package')], max_length=7)),
                ('kcal', models.IntegerField()),
                ('kcal_per_unit', models.CharField(choices=[('PER_100_ML', 'Per 100 ml'), ('PER_100_MG', 'Per 100 mg'), ('PER_PACKAGE', 'Per package')], max_length=11)),
            ],
        ),
    ]
