# Generated by Django 3.2.3 on 2021-06-29 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_food_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTrackerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.meal')),
            ],
            options={
                'verbose_name_plural': 'Meal tracker entries',
            },
        ),
    ]
