# Generated by Django 3.2.3 on 2021-06-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_meal_tracker_entry_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtrackerentry',
            options={'verbose_name_plural': 'Meal tracker entries'},
        ),
    ]
