# Generated by Django 3.2.3 on 2021-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_body_mass_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('STOCK', 'Stock'), ('CRYPTO', 'Crypto')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='AssetOrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_volume', models.FloatField()),
                ('price', models.FloatField()),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='app.asset')),
            ],
        ),
    ]
