# Generated by Django 3.2.3 on 2021-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_asset_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTrackerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('market_price', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_entries', to='app.asset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assettrackerentry',
            constraint=models.UniqueConstraint(fields=('asset', 'date'), name='unique_asset_date_entry'),
        ),
    ]
