# Generated by Django 3.2.5 on 2021-07-28 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_asset_tracker_entry_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriesGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_goal', models.PositiveSmallIntegerField()),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
