# Generated by Django 3.2.5 on 2021-07-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_calories_goal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtrackerentry',
            name='calories_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='app.caloriesgoal'),
        ),
    ]
