# Generated by Django 3.2.5 on 2021-08-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_add_calories_goal_field_to_meal_tracker_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlanActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.dayplan')),
            ],
        ),
        migrations.CreateModel(
            name='DayGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('goals_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='app.daygoals')),
            ],
        ),
    ]
