# Generated by Django 3.2.5 on 2021-08-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_add_day_plan_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplanactivity',
            name='type',
            field=models.CharField(choices=[('MORNING_ROUTINE', 'Morning routine'), ('EVENING_ROUTINE', 'Evening routine'), ('MEAL', 'Meal'), ('SCHOOL', 'School'), ('LEISURE', 'Leisure'), ('WORKOUT', 'Workout'), ('JOB', 'Job'), ('HOBBY', 'Hobby'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
    ]
