# Generated by Django 3.2.5 on 2021-08-21 15:50

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_type_to_day_plan_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlanTemplateActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('MORNING_ROUTINE', 'Morning routine'), ('EVENING_ROUTINE', 'Evening routine'), ('MEAL', 'Meal'), ('SCHOOL', 'School'), ('LEISURE', 'Leisure'), ('WORKOUT', 'Workout'), ('JOB', 'Job'), ('HOBBY', 'Hobby'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('day_plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.dayplantemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
