# Generated by Django 3.2.5 on 2021-08-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_add_day_plan_template_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='kcal_per',
            new_name='nutrition_per',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
    ]
