# Generated by Django 3.2.7 on 2022-04-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_use_timezone_for_default_created_at_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplanactivity',
            name='ended_at',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dayplanactivity',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dayplanactivity',
            name='started_at',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
