# Generated by Django 3.2.7 on 2022-05-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_add_started_ended_at_and_skipped_fields_to_day_plan_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayplanactivity',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='dayplantemplateactivity',
            options={'ordering': ['start_time']},
        ),
    ]
